### ISSUE TITLE
token storage

### ISSUE THREAD

**Issue by vladislavs1321** [gregurco/GuzzleBundleOAuth2Plugin#10]
is it possible to have default token storage/cache to prevent each api call producing new token?

**Comment by gregurco** [comment]
@vladislavs1321 good proposal :+1: gonna to do it as soon as will have time

**Comment by vladislavs1321** [comment]
@gregurco, sorry for disturbing.  Any news? Quite sensitive problem for me)

**Comment by gregurco** [comment]
@vladislavs1321 hello. I'm thinking about this problem. I have some ideas and let me try to do a concept today/tomorrow. I will write here the result.

**Comment by gregurco** [comment]
@vladislavs1321 I did changes on branch https://github.com/gregurco/GuzzleBundleOAuth2Plugin/tree/persistent_storage .
Please do `composer require gregurco/guzzle-bundle-oauth2-plugin dev-persistent_storage`
and setup plugin to be "persistent":
```yaml
eight_points_guzzle:
    clients:
        your_client_name:
            # ...
            
            plugin:
                oauth2:
                    # your configuration
                    persistent:  true
```

So, in this case access token will be persisted in session (not token storage) and used in future requests... Please write feedback after testing if you are able to test to know if it's ok and ready to merge and release.
