### ISSUE TITLE
Bad client used ?

### ISSUE THREAD

**Issue by adpeyre** [gregurco/GuzzleBundleOAuth2Plugin#26]
Hi,

I set "verify" to false but OAuth2Plugin seems do not use the good client.

**Comment by gregurco** [comment]
Hello

@adpeyre could you please share more information? Where do you setup "verify"? Which client is used and which should be used? etc.

**Comment by adpeyre** [comment]
Hello @gregurco !

I share my configuration, It's easier. :)

``` yaml
eight_points_guzzle:
    clients:
        erp:
            base_url: '%env(ERP_API_BASE_URL)%'
            # Request options: http://docs.guzzlephp.org/en/stable/request-options.html
            options:
                auth: oauth2
                verify: false

            # Find plugins here:
            # https://github.com/8p/EightPointsGuzzleBundle#known-and-supported-plugins
            plugin:
                # More information: https://packagist.org/packages/gregurco/guzzle-bundle-oauth2-plugin
                oauth2:
                    base_uri: '%env(ERP_API_OAUTH_BASE_URL)%'
                    token_url: "/connect/token"
                    client_id: '%env(ERP_API_OAUTH_CLIENT_ID)%'
                    client_secret: '%env(ERP_API_OAUTH_CLIENT_SECRET)%'
                    username: '%env(ERP_API_OAUTH_USERNAME)%'
                    password: '%env(ERP_API_OAUTH_PASSWORD)%'
                    #scope: "administration"
                    grant_type: "Sainsburys\\Guzzle\\Oauth2\\GrantType\\PasswordCredentials"
                    auth_location: 'body'
                    persistent: true

```

Curl options defined for the client (erp) are not used by the plugin.
For example, in this configuration, "verify: false" is not used by the OAuth2 plugin. 

Is there a solution for that ?
